export const COLORS = [
    { name: 'Red', class: 'bg-red-500', hex: '#EF4444' },
    { name: 'Orange', class: 'bg-orange-500', hex: '#F97316' },
    { name: 'Yellow', class: 'bg-yellow-400', hex: '#FACC15' },
    { name: 'Green', class: 'bg-green-500', hex: '#22C55E' },
    { name: 'Blue', class: 'bg-blue-500', hex: '#3B82F6' },
    { name: 'Purple', class: 'bg-purple-500', hex: '#A855F7' },
    { name: 'Pink', class: 'bg-pink-500', hex: '#EC4899' },
];

export const FANTASY_LOCATIONS = [
    "Random",
    "The Crystal Cave",
    "The Enchanted Forest",
    "Rainbow Valley",
    "The Starry Moon Base",
    "Underwater Kingdom",
    "Chocolate Mountain",
    "The Flying Castle",

    "The Whispering Woods",
    "The Frozen Star Lake",
    "The Cloudstep Meadows",
    "The Golden Lantern Village",
    "The Hidden Moon Garden",
    "The Emerald River Path",
    "The Sunbeam Canyon",
    "The Dreamweaver Desert",
    "The Sapphire Waterfalls",
    "The Featherlight Cliffs",
    "The Glowstone Marsh",
    "The Stardust Dunes",
    "The Singing Crystal Ridge",
    "The Timeless Clocktower Realm",
    "The Secret Pumpkin Hollow",
    "The Floating Lantern Marshes",
    "The Luminous Coral City",
    "The Starwhisper Observatory",
    "The Velvet Twilight Grove",
    "The Echoing Dragon Caverns",
    "The Aurora Blossom Fields",
    "The Misty Moonlit Harbor",
    "The Ancient Tree of Wishes",
    "The Lavender Cloud Isles",
    "The Harmony Hills Sanctuary",
    "The Midnight Feather Forest",
    "The Blossomwind Valley",
    "The Stardrop Mountain Range",
    "The Golden Leaf Springs",
    "The Eternal Firefly Village",
    "The Cotton Candy Coast",
    "The Frostpetal Meadow",
    "The Sunken Robot Ruins",
    "The Painted Rainbow Shoreline",
    "The Star Lantern Lagoon",
    "The Crystal Owl Observatory",
    "The Enchanted Mushroom Grove",
    "The Glittering Snowpeak Mountains",
    "The Secret Whimsy Workshop",
    "The Silver Phoenix Plateau",
    "The Stardust Orchard",
    "The Magic Lantern Canyon",
    "The Spiral Moon Oasis",
    "The Whispering Cloud Palace",
    "The Shimmering Wind Tunnels",
    "The Rainbow Tree Canopy",
    "The Firefly-Mirror Lake",
    "The Celestial Dragon Gardens",
    "The Wooly Mammoth Valley",
    "The Snowglobe Village",
    "The Marshmallow Volcano",
    "The Royal Pegasus Fields",
    "The Star-Thread Needle Forest",
    "The Honeydrop Hills",
    "The Electric Jellyfish Bay",
    "The Cometfall Bridge",
    "The Sunflower Castle",
    "The Time-Twisted Playground",
    "The Midnight Starlace River",
    "The Whispering Teapot Village",
    "The Coral Blossom Ridge",
    "The Ice-Cream Cloud Realm",
    "The Hidden Rainbow Lagoon",
    "The Glowing Moss Caverns",
    "The Moonstone Orchard",
    "The Cottoncloud Harbor",
    "The Spinning Top Mountains",
    "The Shimmerleaf Sanctuary",
    "The Enchanted Turtle Docks",
    "The Glitterwind Peninsula",
    "The Songbird Crystal Tower",
    "The Frozen Bubble Valley",
    "The Stargazer’s Mirror Desert",
    "The Dreamcatcher Isles",
    "The Ruby Ember Garden",
    "The Floating Cloud Train Station",
    "The Marshmallow Tree Plains",
    "The Sapphire Dream City",
    "The Bubblegum Star Station",
    "The Dandelion Wind Temple",
    "The Moonlit Firefly Bridge",
    "The Lullaby Lake District",
    "The Starlit Lantern Peaks",
    "The Mystic Quartz Garden",
    "The Echopearl Shore",
    "The Galactic Meadow Plains",
    "The Crystal-Frost Observatory",
    "The Enchanted Storybook Library",
    "The Glowing Seashell Coastline",
    "The Starglow Fox Burrow",
    "The Solar Unicorn Valley",
    "The Mistwhisper Wetlands",
    "The Twilight Honeycomb Hills",
    "The Celestial Feather Lagoon",
    "The Pirate Cloud Archipelago",
    "The Dragonfruit Jungle",
    "The Sunbeam Crystal Port",
    "The Clockwork Star Village",
    "The Rainbow Bridge Isles",
    "The Moonlit Robot Gardens",
    "The Phoenix Ember Coast",
    "The Frosted Dreamscape Mountain",
    "The Harmonic Breeze Village",
    "The Enchanted Toymaker’s City",
    "The Fluffylight Polar Ridge",
    "The Starborn Melody Fields",
    "The Radiant Glow River",
    "The Lunar Blossom Terrace",
    "The Celestial Seedling Forest",
    "The Whisperwind Floating Bazaar",
    "The Magical Acorn Kingdom",
    "The Prismtail Reef",
    "The Enchanted Carousel Mountains",
    "The Moonrise Bubble Harbor",
    "The Rainbow-Thread Forest",
    "The Spellsong Fountain District",
    "The Silvercloud Temple",
    "The Pumpkin Spice Kingdom",
    "The Hidden Starlace Canals",
    "The Velvet Ember Citadel",
    "The Pearlspire Grotto",
    "The Glimmergrove Highlands",
    "The Crystal Phoenix Lake",
    "The Frostwind Echo Peaks",
    "The Whirlwind Cotton Valley",
    "The Storyteller’s Golden Tower",
    "The Twilight Unicorn Pavilion",
    "The Lanternlit Cherry Forest",
    "The Galactic Candy Mines",
    "The Perfume Blossom Bay",
    "The Timeless Snow Owl Shrine",
    "The Dancing Aurora Village",
    "The Enchanted River of Wishes",
    "The Firefly Garden Observatory",
    "The Moondrop Tea Village",
    "The Singing Shell Coast",
    "The Stardust Fire Garden",
    "The Glowing Harmony Fortress",
    "The Pastel Dream Harbor",
    "The Whispermist Cliffside",
    "The Cloudwhirl Castle",
    "The Sun-Kissed Dragon Bridge",
    "The Golden Acorn Resting Grounds",
    "The Prismflower Ocean Trench",
    "The Enchanted Willow Parade",
    "The Skywhispering Falls"
];


export const COMPANION_PRESETS = [
    { label: 'Dog', text: 'a loyal puppy named Spot', icon: 'fa-dog', color: 'text-orange-400' },
    { label: 'Cat', text: 'a clever cat named Whiskers', icon: 'fa-cat', color: 'text-gray-300' },
    { label: 'Dragon', text: 'a friendly tiny dragon', icon: 'fa-dragon', color: 'text-red-500' },
    { label: 'Unicorn', text: 'a sparkling unicorn', icon: 'fa-horse', color: 'text-pink-400' },

    // ✔ 50 NEW COMPANIONS
    { label: 'Fairy', text: 'a glowing fairy friend', icon: 'fa-wand-magic-sparkles', color: 'text-purple-400' },
    { label: 'Robot', text: 'a tiny helpful robot', icon: 'fa-robot', color: 'text-blue-400' },
    { label: 'Phoenix', text: 'a warm-hearted baby phoenix', icon: 'fa-fire', color: 'text-red-400' },
    { label: 'Mermaid', text: 'a playful mini mermaid', icon: 'fa-water', color: 'text-cyan-300' },
    { label: 'Elf', text: 'a cheerful little elf', icon: 'fa-hat-wizard', color: 'text-green-400' },
    { label: 'Gnome', text: 'a tiny garden gnome', icon: 'fa-tree', color: 'text-emerald-400' },
    { label: 'Owl', text: 'a wise owl with big eyes', icon: 'fa-kiwi-bird', color: 'text-yellow-400' },
    { label: 'Fox', text: 'a curious little fox', icon: 'fa-paw', color: 'text-orange-500' },
    { label: 'Penguin', text: 'a waddling baby penguin', icon: 'fa-snowflake', color: 'text-sky-300' },
    { label: 'Lion Cub', text: 'a brave little lion cub', icon: 'fa-paw', color: 'text-yellow-500' },
    { label: 'Dinosaur', text: 'a tiny friendly dinosaur', icon: 'fa-hippo', color: 'text-green-500' },
    { label: 'Butterfly', text: 'a magical glowing butterfly', icon: 'fa-wand-magic', color: 'text-purple-300' },
    { label: 'Turtle', text: 'a gentle explorer turtle', icon: 'fa-shield-turtle', color: 'text-green-300' },
    { label: 'Bear Cub', text: 'a cuddly bear cub', icon: 'fa-paw', color: 'text-brown-400' },
    { label: 'Mouse', text: 'a tiny shy mouse', icon: 'fa-paw', color: 'text-gray-400' },
    { label: 'Squirrel', text: 'a nut-loving squirrel', icon: 'fa-paw', color: 'text-amber-500' },
    { label: 'Frog', text: 'a jumpy green frog', icon: 'fa-frog', color: 'text-green-600' },
    { label: 'Star Spirit', text: 'a floating star spirit', icon: 'fa-star', color: 'text-yellow-300' },
    { label: 'Snow Sprite', text: 'a tiny snow sprite', icon: 'fa-snowflake', color: 'text-blue-200' },
    { label: 'Cloud Puff', text: 'a fluffy cloud creature', icon: 'fa-cloud', color: 'text-gray-200' },
    { label: 'Mini Witch', text: 'a tiny witch with a sparkly hat', icon: 'fa-hat-wizard', color: 'text-purple-500' },
    { label: 'Knightling', text: 'a small knight with a big heart', icon: 'fa-shield-heart', color: 'text-blue-500' },
    { label: 'Alien', text: 'a cute green alien buddy', icon: 'fa-user-astronaut', color: 'text-lime-400' },
    { label: 'Astronaut Bear', text: 'a bear in a tiny spacesuit', icon: 'fa-helmet-safety', color: 'text-indigo-400' },
    { label: 'Magic Wolf Pup', text: 'a glowing wolf pup', icon: 'fa-wolf-pack-battalion', color: 'text-blue-300' },
    { label: 'Crystal Sprite', text: 'a shimmering crystal sprite', icon: 'fa-gem', color: 'text-cyan-400' },
    { label: 'Shadow Kitten', text: 'a mysterious shadow kitten', icon: 'fa-cat', color: 'text-purple-700' },
    { label: 'Wind Spirit', text: 'a swirling wind spirit', icon: 'fa-wind', color: 'text-sky-400' },
    { label: 'Fire Sprite', text: 'a warm fiery sprite', icon: 'fa-fire-flame-curved', color: 'text-red-600' },
    { label: 'Water Nymph', text: 'a tiny water nymph', icon: 'fa-droplet', color: 'text-blue-300' },
    { label: 'Earth Golemling', text: 'a small earthy golem', icon: 'fa-mountain', color: 'text-amber-700' },
    { label: 'Mini Griffin', text: 'a little griffin with tiny wings', icon: 'fa-dove', color: 'text-yellow-400' },
    { label: 'Baby Pegasus', text: 'a flying baby pegasus', icon: 'fa-feather', color: 'text-pink-300' },
    { label: 'Crystal Bird', text: 'a bird with shimmering crystal feathers', icon: 'fa-dove', color: 'text-sky-200' },
    { label: 'Glow Worm', text: 'a glowing worm guide', icon: 'fa-lightbulb', color: 'text-amber-300' },
    { label: 'Firefly', text: 'a tiny golden firefly', icon: 'fa-bug', color: 'text-yellow-200' },
    { label: 'Sea Otter', text: 'a playful sea otter', icon: 'fa-fish', color: 'text-teal-400' },
    { label: 'Octopus Kid', text: 'a tiny purple octopus friend', icon: 'fa-fish', color: 'text-purple-400' },
    { label: 'Mini Giant', text: 'a giant… but tiny!', icon: 'fa-child-reaching', color: 'text-gray-400' },
    { label: 'Crystal Fox', text: 'a fox made of shimmering ice crystals', icon: 'fa-paw', color: 'text-blue-200' },
    { label: 'Lightning Sprite', text: 'a sparking lightning sprite', icon: 'fa-bolt', color: 'text-yellow-400' },
    { label: 'Sand Gnome', text: 'a sandy dune gnome', icon: 'fa-mountain-sun', color: 'text-amber-600' },
    { label: 'Mini Yeti', text: 'a fluffy mini yeti', icon: 'fa-snowflake', color: 'text-blue-100' },
    { label: 'Star Bunny', text: 'a bunny that glows like a star', icon: 'fa-star-of-life', color: 'text-yellow-300' },
    { label: 'Moon Mouse', text: 'a mouse from the moon', icon: 'fa-moon', color: 'text-indigo-300' },
    { label: 'Sun Cub', text: 'a cub born from sunlight', icon: 'fa-sun', color: 'text-amber-400' },
    { label: 'Jelly Blob', text: 'a bouncy magical jelly blob', icon: 'fa-apple-whole', color: 'text-pink-300' },

    // ✔ RANDOM OPTIONS
    { label: 'Random Cute Animal', text: 'a cute random animal friend', icon: 'fa-shuffle', color: 'text-teal-300' },
    { label: 'Random Fantasy Creature', text: 'a random magical creature', icon: 'fa-wand-magic-sparkles', color: 'text-purple-400' },
    { label: 'Random Companion', text: 'a mysterious random companion', icon: 'fa-random', color: 'text-gray-300' }
];


export const STORY_TONES = [
    { id: 'heroic', label: 'Heroic Quest', desc: 'Epic adventures full of bravery.', icon: 'fa-shield-halved', color: 'text-orange-500', bg: 'bg-orange-500/10 border-orange-500/50' },
    { id: 'royal', label: 'Royal Tale', desc: 'Royal stories filled with kindness.', icon: 'fa-crown', color: 'text-yellow-400', bg: 'bg-yellow-400/10 border-yellow-400/50' },
    { id: 'sparkle', label: 'Magical Sparkle', desc: 'Whimsical, sparkly, enchanted tones.', icon: 'fa-wand-magic-sparkles', color: 'text-purple-400', bg: 'bg-purple-400/10 border-purple-400/50' },
    { id: 'cozy', label: 'Cozy Bedtime', desc: 'Soft, sleepy, gentle stories.', icon: 'fa-moon', color: 'text-blue-300', bg: 'bg-blue-300/10 border-blue-300/50' },
    { id: 'funny', label: 'Funny & Silly', desc: 'Goofy, playful, laugh-filled moments.', icon: 'fa-face-laugh-beam', color: 'text-yellow-300', bg: 'bg-yellow-300/10 border-yellow-300/50' },
    { id: 'animal', label: 'Animal Friends', desc: 'Cute creatures, warm companionship.', icon: 'fa-paw', color: 'text-green-400', bg: 'bg-green-400/10 border-green-400/50' },
    { id: 'space', label: 'Space Explorer', desc: 'Cosmic adventures among stars.', icon: 'fa-rocket', color: 'text-indigo-400', bg: 'bg-indigo-400/10 border-indigo-400/50' },
    { id: 'mystery', label: 'Mystery Detective', desc: 'Kid-friendly investigations.', icon: 'fa-magnifying-glass', color: 'text-gray-300', bg: 'bg-gray-400/10 border-gray-400/50' },
    { id: 'fairy', label: 'Fairy Forest', desc: 'Nature spirits, fairies, fantasy woodland.', icon: 'fa-leaf', color: 'text-emerald-400', bg: 'bg-emerald-400/10 border-emerald-400/50' },
];


export const PAGE_COUNTS = [
    { value: "4", label: "4 Pages (Short Story)" },
    { value: "6", label: "6 Pages (Standard)" },
    { value: "8", label: "8 Pages (Extended)" },
    { value: "10", label: "10 Pages (Epic)" },
    { value: "12", label: "12 Pages (Novelty)" },
]
