export const PLANS = [
    {
        id: "2-month",
        title: "2-month plan",
        subtitle: "40 Credits every two months",
        price: 53,
        originalPrice: 154,
        tag: "Special value - save 50",
        period: "per moment",
        credits: 40,
        interval: "2-month",
    },
    {
        id: "1-month",
        title: "1-month plan",
        subtitle: "20 Credits every month",
        price: 66,
        originalPrice: 166,
        tag: "Special value - save 50",
        period: "per moment",
        credits: 20,
        interval: "1-month",
    },
    {
        id: "weekly",
        title: "Weekly plan",
        subtitle: "4 Credits every week",
        price: 205,
        originalPrice: null,
        tag: null,
        period: "per moment",
        credits: 4,
        interval: "1-week",
    }
] as const;
