export const ROUTES = {
    HOME: '/',
    CREATE: '/create',
    ANIMATION_STYLE: '/animation-style',
    MOMENT_READY: '/moment-ready',
    EMAIL_COLLECTION: '/email-collection',
    QUIZ_FINISHED: '/quiz-finished',
    PRICING: '/pricing',
    ORDER_CONFIRMATION: '/order-confirmation',
    PAYMENT_PROCESSING: '/payment-processing',
    OFFER_CUSTOM_STYLE: '/offer-custom-style',
    OFFER_PRIORITY: '/offer-priority',
    OFFER_COINS: '/offer-coins',
    CREATE_PASSWORD: '/create-password',
    LOGIN: '/login',
    DASHBOARD: '/dashboard',
    GET_COINS: '/get-coins',
    INVITE: '/invite',
    PRIVACY_POLICY: '/privacy-policy',
    TERMS_OF_SERVICE: '/terms-of-service',
} as const;